// @graphnight/native - Native Node.js bindings for GraphNight
// This file is generated by napi-rs during build

const { GraphNightClient } = require('./graphnight.napi');

// Re-export the native class
module.exports = {
  GraphNightClient,
  createClient: (storagePath?: string) => new GraphNightClient(storagePath),
  VERSION: '1.0.0',
};

// TypeScript exports
module.exports.GraphNightClient = GraphNightClient;
module.exports.createClient = (storagePath?: string) => new GraphNightClient(storagePath);
module.exports.VERSION = '1.0.0';