# These are supported funding model platforms

github: [niranjanaryan]
patreon: niranjanaryan
open_collective: graphnight
ko_fi: niranjanaryan
tidelift: graphnight
community_bridge: graphnight
liberapay: niranjanaryan
issuehunt: graphnight
otechie: niranjanaryan
lfx_crowdfunding: graphnight
polar: graphnight
buy_me_a_coffee: niranjanaryan
thanks_dev: niranjanaryan
custom: ["https://github.com/sponsors/niranjanaryan"]