// Native Node.js bindings for GraphNight - Entry point
// This file is generated by napi-rs during build

export * from './graphnight.linux-x64-gnu.node';
export * from './graphnight.linux-arm64-gnu.node';
export * from './graphnight.darwin-x64.node';
export * from './graphnight.darwin-arm64.node';
export * from './graphnight.win32-x64-msvc.node';
export * from './graphnight.freebsd-x64.node';

// Fallback for platforms without prebuilt binaries
try {
  // Try to load the platform-specific binary
  const platform = process.platform;
  const arch = process.arch;
  
  let binaryName;
  if (platform === 'linux') {
    binaryName = arch === 'arm64' ? 'graphnight.linux-arm64-gnu.node' : 'graphnight.linux-x64-gnu.node';
  } else if (platform === 'darwin') {
    binaryName = arch === 'arm64' ? 'graphnight.darwin-arm64.node' : 'graphnight.darwin-x64.node';
  } else if (platform === 'win32') {
    binaryName = 'graphnight.win32-x64-msvc.node';
  } else if (platform === 'freebsd') {
    binaryName = 'graphnight.freebsd-x64.node';
  }
  
  if (binaryName) {
    module.exports = require(`./${binaryName}`);
  }
} catch (e) {
  console.warn('GraphNight native binding not found for this platform. Please build from source.');
}