[package]
name = "graphnight-graphql"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[dependencies]
graphnight-core = { path = "../graphnight-core" }
graphnight-sql = { path = "../graphnight-sql" }
graphnight-storage = { path = "../graphnight-storage" }
async-graphql = { workspace = true }
async-graphql-tide = { workspace = true }
tide = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
futures = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
tempfile = { workspace = true }