[package]
name = "graphnight-sql"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[dependencies]
graphnight-core = { path = "../graphnight-core" }
# datafusion = { workspace = true }
arrow = { workspace = true }
# parquet = { workspace = true }
sqlx = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
dashmap = { workspace = true }
lru = { workspace = true }
parking_lot = { workspace = true }
zstd-safe = { workspace = true }
futures = { workspace = true }
pin-project-lite = { workspace = true }
tracing = { workspace = true }
regex = { workspace = true }
async-stream = { workspace = true }

[dev-dependencies]
pretty_assertions = { workspace = true }
graphnight-storage = { path = "../graphnight-storage" }
tokio = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "sql_generate"
harness = false