[package]
name = "graphnight-server"
version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
authors = { workspace = true }

[[bin]]
name = "graphnight-server"
path = "src/main.rs"

[dependencies]
graphnight-core = { path = "../graphnight-core" }
graphnight-sql = { path = "../graphnight-sql" }
graphnight-storage = { path = "../graphnight-storage" }
graphnight-graphql = { path = "../graphnight-graphql" }
async-graphql = { workspace = true }
async-graphql-axum = { workspace = true }
axum = { workspace = true }
tower-http = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
config = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }
clap = { version = "4.5", features = ["derive"] }
toml = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = "9.3"
reqwest = { version = "0.12", default-features = false, features = [
    "json",
    "rustls-tls",
] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
